### PR TITLE
add delete functionality to meals table

### PR DESCRIPTION
**Pull request by cmacaulay**
❓ 
- test only fails sometimes
Error message:
```
1) Server /api/meals POST /api/meals should return 200:
     Uncaught AssertionError: expected 2 to equal 1
      at Request.request.post [as _callback] (test/meals-response-test.js:306:18)
      at Request.self.callback (node_modules/request/request.js:188:22)
      at Request.<anonymous> (node_modules/request/request.js:1171:10)
      at IncomingMessage.<anonymous> (node_modules/request/request.js:1091:12)
      at endReadableNT (_stream_readable.js:975:12)
      at _combinedTickCallback (internal/process/next_tick.js:80:11)
      at process._tickCallback (internal/process/next_tick.js:104:9)
```

### CODE REVIEW

**Comment by TheKaterTot** [comment]
I'd like to look over this tomorrow with you @cmacaulay because it seems like we've either done something strange to our test or we've found an edge case.

**Comment by cmacaulay** [comment]
@TheKaterTot sounds good

**Comment by TheKaterTot** [comment]
I ran these tests about 20 times, and it failed once. @case-eee I think we've come across something strange in the DB prep, but I'm at a loss for how to troubleshoot it when it's not happening regularly. Basically, we're testing the length of the returned array is 2, but occasionally, it's only 1.

**Comment by TheKaterTot** [comment]
I am going to merge this PR because this failing test is separate from the Delete portion. Really good work @cmacaulay

**Pull request merged**
